language: objective-c

before_install:
  - brew update > /dev/null
  
install:
  - mkdir -p $(brew --repo)/Library/Taps/osrf
  - ln -s $PWD $(brew --repo)/Library/Taps/osrf/homebrew-simulation
  - brew tap --repair
  
script:
  - brew audit `ls $(brew --repo)/Library/Taps/osrf/homebrew-simulation/*.rb | grep -v sofa.rb`
  - brew style `ls $(brew --repo)/Library/Taps/osrf/homebrew-simulation/*.rb`
  - brew fetch --force-bottle `ls $(brew --repo)/Library/Taps/osrf/homebrew-simulation/*.rb | grep -v sofa.rb` | grep -v '%$'
  - brew unpack --patch `ls $(brew --repo)/Library/Taps/osrf/homebrew-simulation/*.rb | grep -v sofa.rb`
  
matrix:
  fast_finish: true
